version: '3.1'
services:
  db:
    image: postgres:13 
    container_name: db_3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass_postgres
      - POSTGRES_USER=user_postgres
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin4_3
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nabi.aqeedat@xtec.cat
      PGADMIN_DEFAULT_PASSWORD : nabi1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

